import 'dart:io';
import 'package:path_provider/path_provider.dart';
import '../models/video_data.dart';
import '../models/video_prediction.dart';
import '../models/hashtag_analysis.dart';
import '../models/video_comparison.dart';

/// Export Service for AI YouTube Boost v2.0
/// Export reports and analytics data
class ExportService {
  /// Export video analytics to CSV
  Future<String> exportVideoAnalyticsToCSV(List<VideoData> videos) async {
    final buffer = StringBuffer();
    
    // CSV Header
    buffer.writeln('Title,Channel,Views,Likes,Comments,Engagement Rate,Published Date,Duration,Category');
    
    // CSV Data
    for (var video in videos) {
      buffer.writeln(
        '"${_escapeCsv(video.title)}",'
        '"${_escapeCsv(video.channelTitle)}",'
        '${video.viewCount},'
        '${video.likeCount},'
        '${video.commentCount},'
        '${video.engagementRate.toStringAsFixed(2)},'
        '${video.publishedAt.toIso8601String()},'
        '${video.duration.inMinutes},'
        '${video.categoryId}',
      );
    }
    
    return _saveFile('video_analytics_${DateTime.now().millisecondsSinceEpoch}.csv', buffer.toString());
  }

  /// Export prediction report to text
  Future<String> exportPredictionReport(VideoPrediction prediction) async {
    final buffer = StringBuffer();
    
    buffer.writeln('═══════════════════════════════════════════════════');
    buffer.writeln('     AI YOUTUBE BOOST v2.0 - PREDICTION REPORT');
    buffer.writeln('═══════════════════════════════════════════════════\n');
    
    buffer.writeln('Video Title: ${prediction.videoTitle}');
    buffer.writeln('Category: ${prediction.category}');
    buffer.writeln('Tags: ${prediction.tags.join(", ")}');
    buffer.writeln('Prediction Date: ${_formatDate(prediction.predictionDate)}');
    buffer.writeln('Timeframe: ${prediction.timeframe.displayName}\n');
    
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln('PERFORMANCE PREDICTIONS');
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln('Predicted Views:     ${prediction.formattedPredictedViews}');
    buffer.writeln('Predicted Likes:     ${_formatNumber(prediction.predictedLikes)}');
    buffer.writeln('Predicted Comments:  ${_formatNumber(prediction.predictedComments)}');
    buffer.writeln('Virality Score:      ${prediction.viralityScore.toStringAsFixed(1)}/100');
    buffer.writeln('Success Probability: ${(prediction.successProbability * 100).toStringAsFixed(1)}%');
    buffer.writeln('Success Level:       ${prediction.successLevel}');
    buffer.writeln('Virality Level:      ${prediction.viralityLevel}\n');
    
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln('ANALYSIS FACTORS');
    buffer.writeln('─────────────────────────────────────────────────');
    prediction.factors.forEach((key, value) {
      if (value is double) {
        buffer.writeln('${_formatFactorName(key)}: ${value.toStringAsFixed(1)}/100');
      }
    });
    
    buffer.writeln('\n─────────────────────────────────────────────────');
    buffer.writeln('AI RECOMMENDATIONS');
    buffer.writeln('─────────────────────────────────────────────────');
    for (var i = 0; i < prediction.recommendations.length; i++) {
      buffer.writeln('${i + 1}. ${prediction.recommendations[i]}');
    }
    
    buffer.writeln('\n═══════════════════════════════════════════════════');
    buffer.writeln('Generated by AI YouTube Boost v2.0');
    buffer.writeln('© 2025 - Advanced AI-Powered Analytics');
    buffer.writeln('═══════════════════════════════════════════════════');
    
    return _saveFile('prediction_report_${DateTime.now().millisecondsSinceEpoch}.txt', buffer.toString());
  }

  /// Export hashtag analysis to text
  Future<String> exportHashtagAnalysis(HashtagAnalysis analysis) async {
    final buffer = StringBuffer();
    
    buffer.writeln('═══════════════════════════════════════════════════');
    buffer.writeln('   AI YOUTUBE BOOST v2.0 - HASHTAG ANALYSIS');
    buffer.writeln('═══════════════════════════════════════════════════\n');
    
    buffer.writeln('Video Title: ${analysis.videoTitle}');
    buffer.writeln('Category: ${analysis.category}');
    buffer.writeln('Analysis Date: ${_formatDate(analysis.analysisDate)}');
    buffer.writeln('Overall Score: ${analysis.overallScore.toStringAsFixed(1)}/100\n');
    
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln('GENERATED HASHTAGS');
    buffer.writeln('─────────────────────────────────────────────────');
    for (var tag in analysis.generatedHashtags) {
      buffer.writeln('${tag.trend.emoji} #${tag.tag}');
      buffer.writeln('   Score: ${tag.score.toStringAsFixed(1)}/100');
      buffer.writeln('   Search Volume: ${tag.formattedSearchVolume}');
      buffer.writeln('   Competition: ${tag.competitionLevelText}');
      buffer.writeln('   Trend: ${tag.trend.displayName}\n');
    }
    
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln('TRENDING HASHTAGS');
    buffer.writeln('─────────────────────────────────────────────────');
    for (var tag in analysis.trendingHashtags) {
      buffer.writeln('${tag.trend.emoji} #${tag.tag} (${tag.formattedSearchVolume})');
    }
    
    buffer.writeln('\n─────────────────────────────────────────────────');
    buffer.writeln('COPY-READY HASHTAGS');
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln(analysis.getHashtagString());
    
    buffer.writeln('\n─────────────────────────────────────────────────');
    buffer.writeln('RECOMMENDATIONS');
    buffer.writeln('─────────────────────────────────────────────────');
    for (var i = 0; i < analysis.recommendations.length; i++) {
      buffer.writeln('${i + 1}. ${analysis.recommendations[i]}');
    }
    
    buffer.writeln('\n═══════════════════════════════════════════════════');
    buffer.writeln('Generated by AI YouTube Boost v2.0');
    buffer.writeln('═══════════════════════════════════════════════════');
    
    return _saveFile('hashtag_analysis_${DateTime.now().millisecondsSinceEpoch}.txt', buffer.toString());
  }

  /// Export comparison report
  Future<String> exportComparisonReport(VideoComparison comparison, List<VideoData> videos) async {
    final buffer = StringBuffer();
    
    buffer.writeln('═══════════════════════════════════════════════════');
    buffer.writeln('   AI YOUTUBE BOOST v2.0 - COMPARISON REPORT');
    buffer.writeln('═══════════════════════════════════════════════════\n');
    
    buffer.writeln('Comparison Date: ${_formatDate(comparison.comparisonDate)}');
    buffer.writeln('Videos Compared: ${comparison.videoIds.length}');
    buffer.writeln('Confidence Score: ${(comparison.confidenceScore * 100).toStringAsFixed(1)}%\n');
    
    final winner = comparison.getWinner();
    final winnerVideo = videos.firstWhere((v) => v.id == winner);
    
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln('🏆 TOP PERFORMER');
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln('Title: ${winnerVideo.title}');
    buffer.writeln('Channel: ${winnerVideo.channelTitle}');
    buffer.writeln('Views: ${winnerVideo.formattedViews}');
    buffer.writeln('Engagement: ${winnerVideo.engagementRate.toStringAsFixed(2)}%');
    
    final winnerMetrics = comparison.metrics[winner]!;
    buffer.writeln('Overall Score: ${winnerMetrics.overallScore.toStringAsFixed(1)}/100');
    buffer.writeln('Grade: ${winnerMetrics.getGrade()}\n');
    
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln('DETAILED ANALYSIS');
    buffer.writeln('─────────────────────────────────────────────────\n');
    
    for (var video in videos) {
      final metrics = comparison.metrics[video.id];
      if (metrics != null) {
        buffer.writeln('Video: ${video.title}');
        buffer.writeln('  Grade: ${metrics.getGrade()}');
        buffer.writeln('  Overall Score: ${metrics.overallScore.toStringAsFixed(1)}/100');
        buffer.writeln('  Views Score: ${metrics.viewsScore.toStringAsFixed(1)}/100');
        buffer.writeln('  Engagement Score: ${metrics.engagementScore.toStringAsFixed(1)}/100');
        buffer.writeln('  Retention Score: ${metrics.retentionScore.toStringAsFixed(1)}/100');
        buffer.writeln('  Thumbnail Score: ${metrics.thumbnailScore.toStringAsFixed(1)}/100');
        buffer.writeln('  Title Score: ${metrics.titleScore.toStringAsFixed(1)}/100\n');
      }
    }
    
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln('AI RECOMMENDATIONS');
    buffer.writeln('─────────────────────────────────────────────────');
    buffer.writeln(comparison.recommendation ?? 'No recommendations available');
    
    buffer.writeln('\n═══════════════════════════════════════════════════');
    buffer.writeln('Generated by AI YouTube Boost v2.0');
    buffer.writeln('═══════════════════════════════════════════════════');
    
    return _saveFile('comparison_report_${DateTime.now().millisecondsSinceEpoch}.txt', buffer.toString());
  }

  // Helper methods
  String _escapeCsv(String value) {
    return value.replaceAll('"', '""');
  }

  String _formatDate(DateTime date) {
    return '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')} '
           '${date.hour.toString().padLeft(2, '0')}:${date.minute.toString().padLeft(2, '0')}';
  }

  String _formatNumber(int number) {
    if (number >= 1000000) {
      return '${(number / 1000000).toStringAsFixed(1)}M';
    } else if (number >= 1000) {
      return '${(number / 1000).toStringAsFixed(1)}K';
    }
    return number.toString();
  }

  String _formatFactorName(String name) {
    return name.replaceAllMapped(
      RegExp(r'([A-Z])'),
      (match) => ' ${match.group(0)}',
    ).trim();
  }

  Future<String> _saveFile(String filename, String content) async {
    try {
      final directory = await getApplicationDocumentsDirectory();
      final file = File('${directory.path}/$filename');
      await file.writeAsString(content);
      return file.path;
    } catch (e) {
      throw Exception('Failed to save file: $e');
    }
  }
}
